node_js:
- 0.10
before_script:
- npm install -g grunt-cli
- git submodule update --init --recursive
language: node_js
env:
  global:
  - secure: DLTUDc0r6zxMd5awyCOFQaFrZJ3O8tWqLNpVcybRVHsv2UUmFpcvgSzgVNItFyC+bVsZX0X8Gvs7OFtnk0d5ju4zV6aaU+T9VuDvkHmFmAr7ZO0qNtQz/Ncm575Sq4EzXTgdqpMLTWHJJe1KwBT2SrUDRRbhZktnmQkxTmvd2Bo=
  - secure: Jdtb/Lk3sosJYRSUe1VzxAY7Fa4LIPlKUeI2TOXgZT9fKBt9nEwaeIgDp3k45RLA4tHziDUq8b5a/gcocNpfCtKtFL5G24oD0Geccgtlcc4SbKZ6e5jHD5A06lRshUhCundNHUEkRfiX+Mn7T0GILxJ3fYnn4PUF+cckTiB9/dI=
